auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
    path('login/', views.Login.as_view()),
    path('logout/', views.Logout.as_view()),
    path('signup/', views.signup)
]

bitlinks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path, include

from main import views

urlpatterns = [
    path('auth/', include('auth.urls')),
    path('<str:url>', views.fetch),
    path('', views.get_url)
]

main/models.py
from django.db import models

# Create your models here.

class Database(models.Model):
    
    shortened_url = models.CharField(max_length=16, blank = True, primary_key = True)
    actual_url = models.URLField(max_length=2048)
    is_private = models.BooleanField(default=False)
    num_clicks = models.IntegerField(default=0)
    tom = models.TimeField(auto_now_add=True)
    dom = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.shortened_url

main/forms.py
from django import forms
from django.conf import settings

from main import models

my_domain = settings.MY_DOMAIN

class Urlform(forms.ModelForm):
    class Meta :
        model = models.Database
        fields = ['actual_url', 'shortened_url', 'is_private']
        widgets = {
            'actual_url': forms.URLInput(
                attrs={
                    'placeholder': "https://www.google.co.in", 
                    'class': 'form-control',
                }
            ),
            'shortened_url': forms.TextInput(attrs={'placeholder': my_domain + "/_____", 'class': 'form-control',}),
        }
        error_messages = {
            'shortened_url': {
                'unique': "This CustomUrl is already reserved."
            }
        }

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from main import models
from django.contrib.auth.decorators import login_required
from main.forms import Urlform
from django.conf import settings
import random

my_domain = settings.MY_DOMAIN

# Create your views here.
@login_required
def fetch_private(request, model, url):
    print('\n\n\nreached here tooooo\n\n\n')
    actual_url = model.actual_url
    model.num_clicks += 1
    model.save()
    return None

def fetch(request, url):
    try:
        model = models.Database.objects.get(shortened_url = url)
    except:
        return render(request, 'notfound.html')

    if model.is_private :
        if request.user.is_authenticated :
            actual_url = model.actual_url
            model.num_clicks += 1
            model.save()
            return redirect(actual_url)
        else:
            print('\n\n\nreached here\n\n\n')
            return fetch_private(request, model, url)
    actual_url = model.actual_url
    model.num_clicks += 1
    model.save()
    return redirect(actual_url)
    
def generate_random():
    short_url = ""
    for i in range(5):
        x = random.randint(65, 90)
        y = random.randint(97, 122)
        ch = random.randint(1,2)
        if ch == 1:
            short_url += chr(x)
        else :
            short_url += chr(y)
    return short_url

def get_url(request):
    context = {}
    urlform = Urlform()
    short_url = ""
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        urlform = Urlform(request.POST)
        # check whether it's valid:
        if urlform.is_valid():
            model = models.Database()
            if urlform.cleaned_data['shortened_url']:
                short_url = urlform.cleaned_data['shortened_url']
                if short_url.__contains__('/'):
                    urlform.errors['shortened_url'] = ['can contain only alphabets, numbers and "_" ']
                else:
                    model.shortened_url = short_url
                    model.actual_url = urlform.cleaned_data['actual_url']
                    model.is_private = urlform.cleaned_data['is_private']
                    context['short_url']= my_domain + short_url
                    model.save()
            else: 
                short_url = generate_random()
                try:
                    while model.objects.get(shortened_url = short_url):
                        short_url = generate_random()
                except:
                    pass
            
                model.shortened_url = short_url
                model.actual_url = urlform.cleaned_data['actual_url']
                model.is_private = urlform.cleaned_data['is_private']
                context['short_url']= my_domain + '/' + short_url
                model.save()
    
    context['form'] = urlform
    return render(request, 'index.html',context)

templates/index.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="row pt-5">

    <div class="col-2"></div>

    <div class="col-8">

        <div class="card lg" style="width: 50rem;">
            <div class="card-body">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_actual_url">
                            <h1>Paste the URL to be shortened</h1>
                            <span style="color: red">{% for error in form.errors.actual_url %}
                                *{{error}}
                                {% endfor %}
                            </span>
                        </label>
                        {{form.actual_url}}
                        <p class="text-muted">Only http and https links are allowed</p>
                    </div>
                    <div class="form-group">
                        <label for="id_shortened_url">
                            <h4>Enter custom ShortUrl here(optional)</h4>
                            <span style="color: red">{% for error in form.errors.shortened_url %}
                                *{{error}}
                                {% endfor %}
                            </span>
                        </label>
                        {{form.shortened_url}}
                        <p class="text-muted">Leave empty to generate random ShortUrl</p>
                    </div>

                    <div class="form-group">
                        <label for="id_is_private">
                            Make it a private url? <small class="text-muted">(Login Required)</small>
                        </label>
                        {{form.is_private}}
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Get ShortURL</button>
                    </div>
                    {% if form.errors.non_field_errors %}
                    <div class = "form-group">
                        <span style="color: red">{% for error in form.non_field_errors %}
                            *{{error}}
                            {% endfor %}</span>
                    </div>
                    {% endif %}
                    {% if short_url and not form.errors%}
                    <div class = "form-group">
                        <input type="text" readonly class="form-control-plaintext" id="id_short_url"
                            onclick="this.select()" value={{short_url}}>
                        {% if request.method == 'POST' %}
                            <button class = "btn btn-outline-warning" type="button" onclick='func("id_short_url")'> copy</button>
                        {% endif %}
                    </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function func(id) {
        var copyText = document.getElementById(id);
        copyText.select();
        document.execCommand("copy");
        // alert("Copied the text: " + copyText.value);

    }
</script>

{% endblock %}

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    <title>MyLinks</title>
</head>

<body style="font-family: 'Merriweather', serif;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/"> <span style="color: green"> MyLinks </span>|| URL Shortner</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto"></ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">My Shortlinks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Create Grouped Urls</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <div class="text-light" style="padding: 0.5em">Hello {{ request.user.first_name }}</div>
                    </li>
                    <li>
                        <a class="btn btn-danger" href="/auth/logout" role="button">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <div class="text-light" style="padding: 0.5em">Hello Guest</div>
                    </li>
                    <li>
                            <a class="btn btn-primary" href="/auth/login" role="button">Login</a>
                            <a class="btn btn-outline-success" href="/auth/signup" role="button">SignUp</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

templates/notfound.html
{% extends 'layouts/base.html' %}

{% block content %}

<h3>Requested Url not found...</h3>

{% endblock %}